apiVersion: v2
name: sonarr
description: Smart PVR for newsgroup and bittorrent users
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/sonarr
icon: https://github.com/Sonarr/Sonarr/blob/phantom-develop/Logo/512.png?raw=true
sources:
  - https://github.com/Sonarr/Sonarr
  - https://github.com/k8s-at-home/container-images
dependencies:
  - name: sonarr
    repository: https://k8s-at-home.com/charts/
    version: 16.3.2

type: application

# Note: k8s-at-home repository is no longer maintained
version: "16.3.2"

# renovate: datasource=github-releases depName=Sonarr/Sonarr
appVersion: "v4.0.13.2932"

keywords:
  - sonarr
  - torrent
  - usenet
